# Generated by Django 4.2.2 on 2023-07-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('texto1', models.TextField(blank=True)),
                ('texto2', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Redacao',
                'verbose_name_plural': 'Redacoes',
            },
        ),
    ]
