# Generated by Django 4.2.2 on 2023-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0002_categoria_redacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='pictures/%y/%m'),
        ),
    ]
