# Generated by Django 4.2.2 on 2023-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redacoes', '0004_rename_redacao_temas_alter_temas_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas',
            old_name='texto1',
            new_name='texto_motivador_1',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='texto2',
            new_name='texto_motivador_2',
        ),
    ]
